# Generated by Django 3.2.21 on 2023-09-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busManage', '0002_auto_20230920_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='bus_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busManage.busroute'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='bus_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busManage.busstop'),
        ),
    ]
