# Generated by Django 3.2.21 on 2023-09-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busManage', '0004_alter_studentlist_classs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRouteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_service_date', models.DateField()),
                ('next_service_date', models.DateField()),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busManage.busroute')),
            ],
        ),
    ]
