# Generated by Django 3.2.21 on 2023-09-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busManage', '0005_busrouteservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='busrouteservice',
            name='is_serviced',
            field=models.BooleanField(default=False),
        ),
    ]
